package Pojos;
// Generated 4/01/2017 09:04:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Accesorios generated by hbm2java
 */
public class Accesorios  implements java.io.Serializable {


     private Integer idaccesorios;
     private String codigoBrras;
     private String nombre;
     private int precioCosto;
     private int cantidad;
     private Set compradetalles = new HashSet(0);

    public Accesorios() {
    }

	
    public Accesorios(String nombre, int precioCosto, int cantidad) {
        this.nombre = nombre;
        this.precioCosto = precioCosto;
        this.cantidad = cantidad;
    }
    public Accesorios(String codigoBrras, String nombre, int precioCosto, int cantidad, Set compradetalles) {
       this.codigoBrras = codigoBrras;
       this.nombre = nombre;
       this.precioCosto = precioCosto;
       this.cantidad = cantidad;
       this.compradetalles = compradetalles;
    }
   
    public Integer getIdaccesorios() {
        return this.idaccesorios;
    }
    
    public void setIdaccesorios(Integer idaccesorios) {
        this.idaccesorios = idaccesorios;
    }
    public String getCodigoBrras() {
        return this.codigoBrras;
    }
    
    public void setCodigoBrras(String codigoBrras) {
        this.codigoBrras = codigoBrras;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPrecioCosto() {
        return this.precioCosto;
    }
    
    public void setPrecioCosto(int precioCosto) {
        this.precioCosto = precioCosto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getCompradetalles() {
        return this.compradetalles;
    }
    
    public void setCompradetalles(Set compradetalles) {
        this.compradetalles = compradetalles;
    }




}


