package Pojos;
// Generated 4/01/2017 09:04:05 PM by Hibernate Tools 4.3.1



/**
 * Compradetalle generated by hbm2java
 */
public class Compradetalle  implements java.io.Serializable {


     private Integer idcompradetalle;
     private Accesorios accesorios;
     private Compras compras;
     private String nombre;
     private String codigobarras;
     private Integer cantidad;
     private long precioCompra;
     private Long total;

    public Compradetalle() {
    }

	
    public Compradetalle(Accesorios accesorios, Compras compras, String nombre, String codigobarras, long precioCompra) {
        this.accesorios = accesorios;
        this.compras = compras;
        this.nombre = nombre;
        this.codigobarras = codigobarras;
        this.precioCompra = precioCompra;
    }
    public Compradetalle(Accesorios accesorios, Compras compras, String nombre, String codigobarras, Integer cantidad, long precioCompra, Long total) {
       this.accesorios = accesorios;
       this.compras = compras;
       this.nombre = nombre;
       this.codigobarras = codigobarras;
       this.cantidad = cantidad;
       this.precioCompra = precioCompra;
       this.total = total;
    }
   
    public Integer getIdcompradetalle() {
        return this.idcompradetalle;
    }
    
    public void setIdcompradetalle(Integer idcompradetalle) {
        this.idcompradetalle = idcompradetalle;
    }
    public Accesorios getAccesorios() {
        return this.accesorios;
    }
    
    public void setAccesorios(Accesorios accesorios) {
        this.accesorios = accesorios;
    }
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigobarras() {
        return this.codigobarras;
    }
    
    public void setCodigobarras(String codigobarras) {
        this.codigobarras = codigobarras;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public long getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(long precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }




}


