package Pojos;
// Generated 4/01/2017 09:04:05 PM by Hibernate Tools 4.3.1



/**
 * Materiales generated by hbm2java
 */
public class Materiales  implements java.io.Serializable {


     private Integer idmateriales;
     private String nombre;
     private String codBarra;
     private Integer preciocost;
     private Integer precioAnonizado;
     private Integer precioPintura;

    public Materiales() {
    }

	
    public Materiales(String nombre, String codBarra) {
        this.nombre = nombre;
        this.codBarra = codBarra;
    }
    public Materiales(String nombre, String codBarra, Integer preciocost, Integer precioAnonizado, Integer precioPintura) {
       this.nombre = nombre;
       this.codBarra = codBarra;
       this.preciocost = preciocost;
       this.precioAnonizado = precioAnonizado;
       this.precioPintura = precioPintura;
    }
   
    public Integer getIdmateriales() {
        return this.idmateriales;
    }
    
    public void setIdmateriales(Integer idmateriales) {
        this.idmateriales = idmateriales;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodBarra() {
        return this.codBarra;
    }
    
    public void setCodBarra(String codBarra) {
        this.codBarra = codBarra;
    }
    public Integer getPreciocost() {
        return this.preciocost;
    }
    
    public void setPreciocost(Integer preciocost) {
        this.preciocost = preciocost;
    }
    public Integer getPrecioAnonizado() {
        return this.precioAnonizado;
    }
    
    public void setPrecioAnonizado(Integer precioAnonizado) {
        this.precioAnonizado = precioAnonizado;
    }
    public Integer getPrecioPintura() {
        return this.precioPintura;
    }
    
    public void setPrecioPintura(Integer precioPintura) {
        this.precioPintura = precioPintura;
    }




}


