package Pojos;
// Generated 4/01/2017 09:04:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idproductos;
     private String nombre;
     private String tipo;
     private String imgPrinci;
     private Set cotizaciondetalles = new HashSet(0);
     private Set abonodetalles = new HashSet(0);
     private Set ventanadetalles = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String nombre) {
        this.nombre = nombre;
    }
    public Productos(String nombre, String tipo, String imgPrinci, Set cotizaciondetalles, Set abonodetalles, Set ventanadetalles) {
       this.nombre = nombre;
       this.tipo = tipo;
       this.imgPrinci = imgPrinci;
       this.cotizaciondetalles = cotizaciondetalles;
       this.abonodetalles = abonodetalles;
       this.ventanadetalles = ventanadetalles;
    }
   
    public Integer getIdproductos() {
        return this.idproductos;
    }
    
    public void setIdproductos(Integer idproductos) {
        this.idproductos = idproductos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getImgPrinci() {
        return this.imgPrinci;
    }
    
    public void setImgPrinci(String imgPrinci) {
        this.imgPrinci = imgPrinci;
    }
    public Set getCotizaciondetalles() {
        return this.cotizaciondetalles;
    }
    
    public void setCotizaciondetalles(Set cotizaciondetalles) {
        this.cotizaciondetalles = cotizaciondetalles;
    }
    public Set getAbonodetalles() {
        return this.abonodetalles;
    }
    
    public void setAbonodetalles(Set abonodetalles) {
        this.abonodetalles = abonodetalles;
    }
    public Set getVentanadetalles() {
        return this.ventanadetalles;
    }
    
    public void setVentanadetalles(Set ventanadetalles) {
        this.ventanadetalles = ventanadetalles;
    }




}


