package Pojos;
// Generated 4/01/2017 09:04:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idproveedor;
     private Ciudad ciudad;
     private Tipodocumento tipodocumento;
     private String nombre;
     private String apellidos;
     private String numeroDocumento;
     private String correoElectronico;
     private String telefono;
     private String direccion;
     private Set comprases = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(Ciudad ciudad, Tipodocumento tipodocumento, String nombre, String numeroDocumento) {
        this.ciudad = ciudad;
        this.tipodocumento = tipodocumento;
        this.nombre = nombre;
        this.numeroDocumento = numeroDocumento;
    }
    public Proveedor(Ciudad ciudad, Tipodocumento tipodocumento, String nombre, String apellidos, String numeroDocumento, String correoElectronico, String telefono, String direccion, Set comprases) {
       this.ciudad = ciudad;
       this.tipodocumento = tipodocumento;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.numeroDocumento = numeroDocumento;
       this.correoElectronico = correoElectronico;
       this.telefono = telefono;
       this.direccion = direccion;
       this.comprases = comprases;
    }
   
    public Integer getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(Integer idproveedor) {
        this.idproveedor = idproveedor;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public Tipodocumento getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(Tipodocumento tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }




}


