package Pojos;
// Generated 4/01/2017 09:04:05 PM by Hibernate Tools 4.3.1



/**
 * Tipoproducto generated by hbm2java
 */
public class Tipoproducto  implements java.io.Serializable {


     private Integer idtipoProducto;
     private String nombre;

    public Tipoproducto() {
    }

    public Tipoproducto(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdtipoProducto() {
        return this.idtipoProducto;
    }
    
    public void setIdtipoProducto(Integer idtipoProducto) {
        this.idtipoProducto = idtipoProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


