package Pojos;
// Generated 4/01/2017 09:04:05 PM by Hibernate Tools 4.3.1



/**
 * Vidrios generated by hbm2java
 */
public class Vidrios  implements java.io.Serializable {


     private Integer idvidrios;
     private String calibre;
     private int preciocost;

    public Vidrios() {
    }

    public Vidrios(String calibre, int preciocost) {
       this.calibre = calibre;
       this.preciocost = preciocost;
    }
   
    public Integer getIdvidrios() {
        return this.idvidrios;
    }
    
    public void setIdvidrios(Integer idvidrios) {
        this.idvidrios = idvidrios;
    }
    public String getCalibre() {
        return this.calibre;
    }
    
    public void setCalibre(String calibre) {
        this.calibre = calibre;
    }
    public int getPreciocost() {
        return this.preciocost;
    }
    
    public void setPreciocost(int preciocost) {
        this.preciocost = preciocost;
    }




}


